---
title: "football"
output:
  pdf_document:
    keep_md: yes
date: "2023-03-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = FALSE)
```

```{r}
# Import Libraries
library(dplyr)
library(tidyr)
library(tidyverse)
library(reshape2)
library(kableExtra)
```
```{r}
# Code
data = read_csv('data/cleaned_match_data.csv')
data$Year = format(as.Date(data$Date, format="%d-%m-%Y"),"%Y")
data_df = data[-c(1)]
data_df$col_ind = c(1:4450)

# # Removed date because it doesnt add any value to data
# len <- 1:nrow(data_df)
# ind = len[seq(1, length(len),8)]
# val_df = data_df[ind,]
# data_df = data_df[-ind,]
# Convert Datatype
data_df$HTR = as.factor(data_df$HTR)
data_df$FTR = as.factor(data_df$FTR)
data_df$HomeTeam = as.factor(data_df$HomeTeam)
data_df$AwayTeam = as.factor(data_df$AwayTeam)
str(data_df)
```

```{r}
year_list <- unique(data_df$Year)
team_list <- unique(data_df$HomeTeam)
temp_df <- data.frame()
sampled_index_list <- list()
for(year in year_list){
  for (team in team_list){
    team_match_df = filter(data_df, Year==year, HomeTeam==team)
    sampled_index = sample(nrow(team_match_df),1)
    sampled_index_list = append(sampled_index_list, team_match_df[sampled_index,"col_ind"]$col_ind)
    temp_df = rbind(temp_df, team_match_df[sampled_index,])
  }
}
```

```{r}
data_df = data_df[-c(temp_df$col_ind),]
```

```{r}
for(year in year_list){
  for (team in team_list){
    team_match_df = filter(data_df, Year==year, AwayTeam==team)
    sampled_index = sample(nrow(team_match_df),1)
    sampled_index_list = append(sampled_index_list, team_match_df[sampled_index,"col_ind"]$col_ind)
    temp_df = rbind(temp_df, team_match_df[sampled_index,])
  }
}
```

```{r}
val_df = temp_df
```

```{r}
numeric_col = unlist(lapply(data_df, is.numeric))

cat("Numerical Columns within dataset: ", colnames(data_df[, numeric_col]),"\n")

cat("Categorical Columns within dataset: ", colnames(data_df[, !numeric_col]))

data_df[,numeric_col] = sapply(data_df[,numeric_col],as.integer)

ds_df <- as.data.frame(apply(data_df[,numeric_col], 2, summary))
ds_df <- ds_df[-c(17)]
write.csv(ds_df, "data/descriptive_stats.csv")
```

```{r distributions-analysis, fig.height=6, fig.width=10, warning=FALSE}
# Distributions Analysis
gg <- 
  ggplot(gather(data_df[,!numeric_col], cols, value), aes(x = value)) + 
       geom_histogram(stat="count") + facet_wrap(.~cols, scales="free", nrow=2)

ggsave(
  file.path("images", "cat_distribution.png"),
  plot = gg,
  width = 12, 
  height = 8, 
  units = "in",
  dpi = 200
)

gg

gg <- 
  ggplot(gather(data_df[, numeric_col], cols, value), aes(x = value)) + 
  geom_histogram() +
  facet_wrap(.~cols, scales="free", nrow=5)

ggsave(
  file.path("images", "num_distribution.png"),
  plot = gg,
  width = 12, 
  height = 8, 
  units = "in",
  dpi = 200
)

gg
```

```{r boxplot, fig.height=10, fig.width=10}
ggplot(gather(data_df[, numeric_col], cols, value), aes(y = value)) + 
       geom_boxplot() + facet_wrap(.~cols, scales="free", nrow=5)+
       theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r correlation-plot, fig.height=14, fig.width=14, warning=FALSE}
# Correlation Plots
upper_panel<-function(x, y){
    points(x,y, pch=19)
}

lower_panel <- function(x, y){
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- round(cor(x, y), digits=2)
    txt <- paste0("R = ", r)
    text(0.5, 0.5, txt)
}

num_data = data_df[,numeric_col]
num_data = cbind(num_data, FTR=data_df$FTR)

# pairs(num_hdp_data[c(1:6)],
#       upper.panel = upper_panel,
#       lower.panel = lower_panel
#       )
# pairs(num_hdp_data[c(7:12)],
#       upper.panel = upper_panel,
#       lower.panel = lower_panel
#       )
# pairs(num_hdp_data[c(13:18)],
#       upper.panel = upper_panel,
#       lower.panel = lower_panel
#       )
# pairs(num_hdp_data[c(19:21)],
#       upper.panel = upper_panel,
#       lower.panel = lower_panel
#       )

gg <- pairs(num_data,
      upper.panel = upper_panel,
      lower.panel = lower_panel)

ggsave(
  file.path("images", "correlation.png"),
  plot = gg,
  width = 14, 
  height = 14, 
  units = "in",
  dpi = 200
)

gg
```

```{r observed-correlation}

pairs(data_df[c("HTHG", "FTHG", "HTAG", "FTAG")],
      upper.panel = upper_panel,
      lower.panel = lower_panel)


pairs(data_df[c("HS", "HST", "AS", "AST")],
      upper.panel = upper_panel,
      lower.panel = lower_panel)

# ggplot(gather(data_df[,["HT", "HST", "AT", "AST"]], cols, value), aes(x = value)) + 
       # geom_histogram(stat="count") + facet_wrap(.~cols, scales="free", nrow=2)
```

```{r  WDL-team, fig.height=14, fig.width=14}
home_team_wins <- as.data.frame(table(filter(data_df, FTR=="H")$HomeTeam))
away_team_wins <- as.data.frame(table(filter(data_df, FTR=="A")$AwayTeam))

team_wins <- cbind(home_team_wins,away_team_wins$Freq)
draw_team_wins <- filter(data_df, FTR=="D")[c("HomeTeam", "AwayTeam")]
colnames(team_wins) <- c("TeamName", "HomeWins", "AwayWins")

team_wins$HomeDraw = as.data.frame(table(draw_team_wins$HomeTeam))$Freq
team_wins$AwayDraw = as.data.frame(table(draw_team_wins$AwayTeam))$Freq

team_wins$HomeLoss <- as.data.frame(table(data_df$HomeTeam))$Freq - team_wins$HomeWins - team_wins$HomeDraw
team_wins$AwayLoss <- as.data.frame(table(data_df$AwayTeam))$Freq - team_wins$AwayWins - team_wins$AwayDraw

team_wins_plot <- melt(team_wins, id.vars = 1)
team_wins_plot$Ground <- substr(team_wins_plot$variable, 1, 4)
team_wins_plot$variable <- substr(team_wins_plot$variable, 5, 8)

ggplot(team_wins_plot, aes(fill=variable, y=value, x=Ground)) + 
    geom_bar(position="fill", stat="identity")+
  facet_wrap(vars(team_wins_plot$TeamName),  scales = "free_x")
```

```{r}
val_home_team_wins <- as.data.frame(table(filter(val_df, FTR=="H")$HomeTeam))
val_away_team_wins <- as.data.frame(table(filter(val_df, FTR=="A")$AwayTeam))

val_team_wins <- cbind(val_home_team_wins,val_away_team_wins$Freq)
val_draw_team_wins <- filter(val_df, FTR=="D")[c("HomeTeam", "AwayTeam")]
colnames(val_team_wins) <- c("TeamName", "HomeWins", "AwayWins")

val_team_wins$HomeDraw = as.data.frame(table(val_draw_team_wins$HomeTeam))$Freq
val_team_wins$AwayDraw = as.data.frame(table(val_draw_team_wins$AwayTeam))$Freq

val_team_wins$HomeLoss <- as.data.frame(table(val_df$HomeTeam))$Freq - val_team_wins$HomeWins - val_team_wins$HomeDraw
val_team_wins$AwayLoss <- as.data.frame(table(val_df$AwayTeam))$Freq - val_team_wins$AwayWins - val_team_wins$AwayDraw

val_team_wins$Home_Strength <- ((val_team_wins$HomeWins*3+val_team_wins$HomeDraw*1) / (
  (val_team_wins$HomeWins+val_team_wins$HomeLoss+val_team_wins$HomeDraw)*3))*100

val_team_wins$Away_Strength <- ((val_team_wins$AwayWins*3+val_team_wins$AwayDraw*1) / (
  (val_team_wins$AwayWins+val_team_wins$AwayLoss+val_team_wins$AwayDraw)*3))*100
```

```{r team-strength, fig.height=10, fig.width=10}
ggplot(val_team_wins, mapping=aes(x = Home_Strength, y = Away_Strength, label = TeamName)) +
  geom_point() +
  geom_text(size = 4, hjust = 0, vjust = 0) +
  labs(x = "Home Strength",
       y = "Away Strength") +
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 5)) + 
  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 5)) + 
  geom_hline(yintercept = 45, color = "black", linetype = "dashed") + 
  geom_vline(xintercept = 50, color = "black", linetype = "dashed") +
  theme_minimal()
```

```{r}
# Remove variables based on correlation and domain
final_df <- data_df[,!(names(data_df) %in% c("FTHG","FTAG", "HS", "AS", "HTR", "Year", "col_ind"))]
final_df2 <- inner_join(final_df, val_team_wins[c("TeamName","Home_Strength")], join_by(HomeTeam==TeamName))
final_df2 <- inner_join(final_df2, val_team_wins[c("TeamName","Away_Strength")], join_by(AwayTeam==TeamName))
str(final_df)
```
```{r}
final_df <- final_df2[-c(1,2)]
```

```{r final-correlation, fig.height=14, fig.width=14}
num_col = unlist(lapply(final_df, is.numeric))
num_data = final_df[,num_col]
pairs(num_data,
      upper.panel = upper_panel,
      lower.panel = lower_panel)
```

```{r category-distribution}
ggplot(data=final_df, aes(x=Home_Strength, fill=FTR)) +
  geom_histogram(position="dodge", binwidth=1, aes(y=after_stat(density)))+
  labs(x = "Home Strength",
       color = "Full Time Result")

ggplot(data=final_df, aes(x=Away_Strength, fill=FTR)) +
  geom_histogram(position="dodge", binwidth=1, aes(y=after_stat(density)))+
  labs(x = "Away Strength",
       color="Full time Result")

ggplot(data=final_df, aes(x=HST, fill=FTR)) +
  geom_histogram(position="dodge", binwidth=1, aes(y=after_stat(density)))+
  labs(x = "Home Team Shots on Target",
       color = "Full time Result")

ggplot(data=final_df, aes(x=AST, fill=FTR)) +
  geom_histogram(position="dodge", binwidth=1, aes(y=after_stat(density)))+
  labs(x = "Away Team Shots on Target",
       color = "Full time Result")
```

```{r home-strength-team}
ggplot(aes(y=reorder(TeamName, Home_Strength), x=Home_Strength,
       fill=Home_Strength),
       data=val_team_wins[order(val_team_wins$Home_Strength, decreasing=TRUE)[1:10],])+
  geom_bar(stat="identity")+
  scale_fill_gradient(low = "cyan", high = "blue")+
  ylab("Team")+xlab("Home Strength")
```
```{r away-strength-team}
ggplot(aes(y=reorder(TeamName, Away_Strength), x=Away_Strength,
       fill=Away_Strength),
       data=val_team_wins[order(val_team_wins$Away_Strength, decreasing=TRUE)[1:10],])+
  geom_bar(stat="identity")+
  scale_fill_gradient(low = "violet", high = "darkblue")+
  ylab("Team")+xlab("Away Strength")
```
